language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
script:
  - "./mvnw clean verify"
branches:
  only:
    - main
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: heroku
  api_key: $HEROKU_APP_KEY
  app: moneytransferhamusit
  on:
    repo: binget/moneytransfer
    branch: main